### ISSUE TITLE
Consider loading config from `.conf.d` folder

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/StemNS#19]
Seems we can have several categories of config: `etld.conf.d`, `bootstrap.conf.d`, and `exit.conf.d`.  This would make packaging cleaner, as per advice from the Whonix devs.

**Comment by JeremyRand** [comment]
@rllola should I do this refactor?

**Comment by rllola** [comment]
I think I am missing some context here. Could you refresh my memory ?

**Comment by JeremyRand** [comment]
> I think I am missing some context here. Could you refresh my memory ?

@rllola See http://www.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/wiki/Dev/Whonix_friendly_applications_best_practices#config.d_support .  Right now, StemNS loads all of its config from two files: `settings_port.py` and `settings_services.py`.  It would be desirable to refactor this so that StemNS loads those configs from all files within a directory, so that Whonix can package default settings without conflicting with config files that the user creates.
